---
apiVersion: v1
kind: Namespace
metadata:
  name: minecraft
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minecraft-server-config
  labels:
    role: service-config
    app: minecraft-server
  namespace: minecraft
data:
  EULA: "TRUE" # Must accept EULA to use this minecraft server
  VERSION: "1.20.1"
  OPS: "SpacePiratePaul" # List of players who are opped
  VIEW_DISTANCE: "16" # The maximum allowed view distance
  SERVER_NAME: "K-Kube Minecraft" # The name of the server
  MAX_PLAYERS: "4" # The maximum number of players allowed
  INITIAL_MEMORY: "1G" # The initial amount of memory allocated
  MAX_MEMORY: "4G" # The maximum amount of memory allocated
  ENABLE_AUTOPAUSE: "TRUE" # Automatically pause the server when no players are online
  MODPACK_PLATFORM: "MODRINTH"
  MODRINTH_MODPACK: "/addons/modpack.mrpack"
  PLUGINS: "/addons/dhs-server.jar"
  MODRINTH_EXCLUDE_FILES: "distanthorizons"
  MAX_TICK_TIME: "-1"
  ONLINE_MODE: "TRUE" # Enable Mojang authentication
  ENABLE_RCON: "false" # Disable RCON for security
  ENABLE_COMMAND_BLOCK: "false" # Disable command blocks unless needed
  ENFORCE_SECURE_PROFILE: "TRUE" # Enforce secure player profiles
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server
  namespace: minecraft
  labels:
    app: minecraft-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-server
  template:
    metadata:
      labels:
        app: minecraft-server
    spec:
      containers:
        - name: minecraft-server
          image: itzg/minecraft-server
          envFrom:
            - configMapRef:
                name: minecraft-server-config
          resources:
            limits:
              memory: 4Gi
              cpu: 2
          stdin: true
          tty: true
          ports:
            - containerPort: 25565
              hostPort: 25565
              protocol: TCP
            - containerPort: 25565
              hostPort: 25565
              protocol: UDP
          volumeMounts:
            - name: minecraft-data
              mountPath: /data
            - name: minecraft-addons
              mountPath: /addons
      volumes:
        - name: minecraft-data
          hostPath:
            path: /home/brark/minecraft-server/goobcraft/minecraft-data
            type: DirectoryOrCreate
        - name: minecraft-addons
          hostPath:
            path: /home/brark/minecraft-server/goobcraft/addons
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-server
  namespace: minecraft
  labels:
    app: minecraft-server
spec:
  type: LoadBalancer
  selector:
    app: minecraft-server
  ports:
    - name: minecraft-tcp
      port: 25565
      targetPort: 25565
      protocol: TCP
    - name: minecraft-udp
      port: 25565
      targetPort: 25565
      protocol: UDP
